# Site settings
title: Daniel Constantinidis
email: daniel.constantinidis@gmail.com
url: https://danielconstantinidis.github.io
description: "This is a personal website dedicated to my online portfolio."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Daniel C.
  location: Barrie, ON
  social: Around The Web
  credits: Open Source

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/danielconstantinidis
  - title: linkedin
    url: https://linkedin.com/in/danielconstantinidis
  - title: facebook
    url: https://facebook.com/daniel.c0nstantinidis
  - title: twitter
    url: https://twitter.com/webdesignbydan

# Postal address (add as many lines as necessary)
address:
  - line: Serving Barrie and the
  - line: Greater Toronto Area

#Credits content
credits: 'Powered by <a href="http://jekyllrb.com">Jekyll</a>'

# Build settings
markdown: kramdown
permalink: pretty
